### ISSUE TITLE
Redisサーバ，goohub，camome，およびcamomeのデータベースをそれぞれ別コンテナとして立ち上げる

### ISSUE THREAD

**Issue by kanzawa2** [nomlab/camome#54]
Created from [AI0386](http://jay.swlab.cs.okayama-u.ac.jp/minutes/474?ai=0386) of minute 474.
+ Redisサーバ，goohub，camome，およびcamomeのデータベースをそれぞれ別コンテナとして立ち上げる．-->(乃村，神澤，西 !:0386)

**Comment by kanzawa2** [comment]
### 現状報告
現在，Dockerfileにgit clone を記述することにより，コンテナ内でcamomeをgit cloneによりダウンロードしようとしている．
camomeの動作には，config以下に，application_settings.ymlとsecrets.ymlが必要となる．しかし，gitHubにはこれらのファイルがなく，テンプレートである，application_settings_sample.ymlとsecrets-example.ymlしか存在しない．このため，camomeコンテナをbuildした後でコンテナ内に，必要となる2つのファイルを作成し，編集する必要がある．
しかし，これを行おうとcamomeコンテナを立ち上げると，" Switch to inspect mode"と表示され，すぐにコンテナが落ちてしまう．

**Comment by kanzawa2** [comment]
kanzawa [10:02 PM] 
# 現状報告
camome，Postgres，Redisのコンテナを立ち上げ，それぞれのコンテナが動作していることを確認した．
しかし，camomeとPostgresの連携が上手くいかず，カレンダのページを開こうとした際にエラーが発生する．
camome+sqlite3の構成でカレンダのページを開いた場合は，エラーは発生せずにカレンダが表示される．
また，手元のgoohubからコンテナとして動作しているRedisサーバにデータを格納できることと，このデータをcamomeから取り出せることを確認した．

コンテナを立ち上げる際に実行したコマンドは以下の通りである．
`docker-compose build`
`docker-compose run web bundle exec rake db:create db:migrate db:seed`
`docker-compose up`
ただし，データベースにsqlite3を用いる場合は，Dockerfileに以下の記述を追加し，上記の2行目のコマンドは実行しない．
`RUN bundle exec rake db:migrate`
`RUN bundle exec rake db:seed`

ここで，camomeコンテナ内のapplication_settings.yml，secrets.yml，database.ymlはDockerfile内でADDすることにより，手元のファイルをコンテナに反映させている．

## 問題点
+ データベースにPostgresDBを用いた場合，camomeでカレンダのページを開こうとした際に，画像のようなエラーが表示される
![image](https://user-images.githubusercontent.com/18207003/30536247-090f64f8-9ca0-11e7-81da-77f51f0ef926.png)

+ 動作確認のためにデータベースにsqlite3を用いた場合，カレンダは表示されるが，camomeからRedisに対してEventをGETするためのJavascriptが動作せず，camomeのカレンダに予定が表示されないことがあった．

今後は，これらの問題の原因を調査し，解決する．

**Comment by Ryota0312** [comment]
redisサーバ，goohub，camome，およびcamomeのデータベースをそれぞれ別コンテナとして立ち上げた．

# 手順
各コンテナを docker-compose を用いて立ち上げる手順を示す．ここでは camome と goohub のイメージが手元に存在していることを前提とする．
1. docker-compose.ymlを以下のように作成する．
```
version: '3'
services:    
  db:
    container_name: db
    image: postgres
    expose:
      - "5432"
      
  web:
    container_name: camome
    image: camome
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - redis
      - db

  redis:
    container_name: redis
    image: redis

  goohub:
    container_name: goohub
    image: goohub
    links:
      - redis
      - web
    volumes:
      - ./goohub:$HOME/.config/goohub
```

2. camomeのデータベースを初期化する．
```
$ docker-compose run web rake db:create db:migrate db:seed
```

3. goohub とそれにリンクされているコンテナを立ち上げ goohub を bash で操作する．
```
$ docker-compose run goohub bash
```

4. goohub の bash で goohub の初期化と Google カレンダの認証を行う．
```
$ goohub init
$ goohub auth
```

5. event を redis に保存する．
```
$ goohub event CALENDAR_ID START_MONTH --output=redis:redis
```

6. camome のカレンダから redis に保存されているイベントを表示できることを確認する．

# 今後の課題
+ camome と goohub のイメージの完成版を DockerHub の nomlab に push する．
  + 現在 camome の設定ファイルがイメージに含まれているため，docker-compose で設定ファイルをマウントする．
  + camome のイメージは手元でビルドするという案もある．
+ goohub のコンテナが立ち上げたあとすぐに停止してしまうため，`docker-compose run goohub bash`で goohub を立ち上げて，bash にアクセスする必要がある．
  + `docker-compose run goohub bash` では goohub とそれにリンクされているコンテナしか立ち上がらないため明示的に camome をリンクする必要がある．
+ camome が redis に保存しているトークンを goohub が使えるようにする．
